easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Athlete
        - App\Entity\Calendar
        - App\Entity\Event
        - App\Entity\League
        - App\Entity\Sport
        - App\Entity\Team
